[[headers]]
for = "/*"
[headers.values]
Cross-Origin-Embedder-Policy = "require-corp"
Cross-Origin-Opener-Policy = "same-origin"

[build]
command = "npm run generate:ci"
publish = "dist"

[[redirects]]
from = "/getting-started"
to = "/docs/getting-started"

[[redirects]]
from = "/syntax-guide"
to = "/docs/syntax-guide"

[[redirects]]
from = "/custom-routing"
to = "/docs/custom-routing"

[[redirects]]
from = "/plugins-and-integrations"
to = "/docs/plugins-and-integrations"

[[redirects]]
from = "/docs"
to = "/docs/getting-started"

[[redirects]]
from = "/new"
to = "https://pr.new/github.com/saurabhdaware/abell-starter"

[[redirects]]
from = "/tutorial/create-portfolio"
to = "/docs/getting-started"

[[redirects]]
from = "/tutorial"
to = "/docs/getting-started"
